In [2]:
import pandas as pd
import os
import numpy as np

In [3]:
PATH = "./wandb_classification_0501_2357.csv"
dataset = pd.read_csv(PATH)

In [4]:
# MNIST

ds = dataset[dataset["dataset"] == "MNIST"]
del ds["Runtime"]
ds = ds[ds.epochs_backward == 5]
ds = ds[(ds.loss_feedback != "DRL") | ((ds.loss_feedback == "DRL") & (ds.learning_rate == 4) & (ds.learning_rate_backward == 0.0002) & (ds.stepsize == 0.04))]
ds = ds[(ds.loss_feedback != "L-DRL") | ((ds.loss_feedback == "L-DRL") & (ds.learning_rate == 4) & (ds.learning_rate_backward == 0.0002) & (ds.stepsize == 0.04))]
ds = ds[~ds.duplicated(subset=["Name", "loss_feedback", "seed", "learning_rate", "learning_rate_backward", "stepsize"])]
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="mean")

dataset                    MNIST
algorithm loss_feedback
BP        DTP            0.98065
DTP       DRL            0.93250
          DTP            0.97308
          L-DRL          0.93284
DTP-BN    DTP            0.97110
FWDTP     DTP            0.89836
FWDTP-BN  DTP            0.97204

In [5]:
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="std")

dataset                     MNIST
algorithm loss_feedback
BP        DTP            0.004036
DTP       DRL            0.000914
          DTP            0.000626
          L-DRL          0.004496
DTP-BN    DTP            0.001490
FWDTP     DTP            0.001146
FWDTP-BN  DTP            0.001424

In [11]:
# MNIST
ds = dataset[dataset["dataset"] == "FashionMNIST"]
del ds["Runtime"]
ds = ds[ds.epochs_backward == 5]
ds = ds[(ds.algorithm != "BP") | ((ds.algorithm == "BP") & (ds.learning_rate == 0.1))]
ds = ds[(ds.loss_feedback != "DRL") | ((ds.loss_feedback == "DRL") & (ds.learning_rate == 4) & (ds.learning_rate_backward == 0.002) & (ds.stepsize == 0.008))]
ds = ds[(ds.loss_feedback != "L-DRL") | ((ds.loss_feedback == "L-DRL") & (ds.learning_rate == 2) & (ds.learning_rate_backward == 0.001) & (ds.stepsize == 0.02))]
ds = ds[~ds.duplicated(subset=["Name", "loss_feedback", "seed", "learning_rate", "learning_rate_backward", "stepsize"])]
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="mean")

dataset                  FashionMNIST
algorithm loss_feedback
BP        DTP                 0.89238
DTP       DRL                 0.83342
          DTP                 0.88272
          L-DRL               0.83514
FWDTP-BN  DTP                 0.88278

In [12]:
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="std")

dataset                  FashionMNIST
algorithm loss_feedback
BP        DTP                0.007128
DTP       DRL                0.001785
          DTP                0.003154
          L-DRL              0.002004
FWDTP-BN  DTP                0.002333

In [9]:
ds = dataset[dataset["dataset"] == "CIFAR10"]
del ds["Runtime"]
ds["algorithm"].unique()
ds = ds[ds.epochs_backward == 5]
ds = ds[(ds.algorithm != "BP") | ((ds.algorithm == "BP") & (ds.learning_rate == 0.02))]
# pd.pivot_table(ds[ds.algorithm == "BP"], values='test accuracy', index=['learning_rate'], columns=['dataset'], aggfunc="mean")
ds = ds[(ds.loss_feedback != "DRL") | ((ds.loss_feedback == "DRL") & (ds.learning_rate == 2) & (ds.learning_rate_backward == 0.004) & (ds.stepsize == 0.008))]
ds = ds[(ds.loss_feedback != "L-DRL") | ((ds.loss_feedback == "L-DRL") & (ds.learning_rate == 0.2) & (ds.learning_rate_backward == 0.0004) & (ds.stepsize == 0.04))]
ds = ds[~ds.duplicated(subset=["Name", "loss_feedback", "seed", "learning_rate", "learning_rate_backward", "stepsize"])]
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="mean")

dataset                  CIFAR10
algorithm loss_feedback
BP        DTP            0.53896
DTP       DRL            0.45598
          DTP            0.48800
          L-DRL          0.45420
DTP-BN    DTP            0.45256
FWDTP     DTP            0.35800
FWDTP-BN  DTP            0.50774

In [76]:
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="std")

dataset                   CIFAR10
algorithm loss_feedback
BP        DTP            0.011425
DTP       DRL            0.004532
          DTP            0.006700
          L-DRL          0.004201
DTP-BN    DTP            0.005097
FWDTP     DTP            0.001032
FWDTP-BN  DTP            0.000918

In [82]:
ds = dataset[dataset["dataset"] == "CIFAR100"]
del ds["Runtime"]
ds["algorithm"].unique()
ds = ds[ds.epochs_backward == 5]
ds = ds[(ds.algorithm != "BP") | ((ds.algorithm == "BP") & (ds.learning_rate == 0.004))]
pd.pivot_table(ds[ds.algorithm == "BP"], values='test accuracy', index=['learning_rate'], columns=['dataset'], aggfunc="mean")
ds = ds[(ds.loss_feedback != "DRL") | ((ds.loss_feedback == "DRL") & (ds.learning_rate == 0.8) & (ds.learning_rate_backward == 0.002) & (ds.stepsize == 0.02))]
ds = ds[(ds.loss_feedback != "L-DRL") | ((ds.loss_feedback == "L-DRL") & (ds.learning_rate == 2) & (ds.learning_rate_backward == 0.0001) & (ds.stepsize == 0.008))]
ds = ds[~ds.duplicated(subset=["Name", "loss_feedback", "seed", "learning_rate", "learning_rate_backward", "stepsize"])]
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="mean")

dataset                  CIFAR100
algorithm loss_feedback
BP        DTP            0.237025
DTP       DRL            0.204780
          DTP            0.229960
          L-DRL          0.206260
DTP-BN    DTP            0.181200
FWDTP     DTP            0.153720
FWDTP-BN  DTP            0.230440

In [83]:
pd.pivot_table(ds, values='test accuracy', index=['algorithm', 'loss_feedback'], columns=['dataset'], aggfunc="std")

dataset                  CIFAR100
algorithm loss_feedback
BP        DTP            0.002213
DTP       DRL            0.001807
          DTP            0.000856
          L-DRL          0.001638
DTP-BN    DTP            0.002082
FWDTP     DTP            0.001192
FWDTP-BN  DTP            0.001869

In [80]:
ds[(ds.algorithm=="BP") & (ds.learning_rate==0.004)]

,Name,dataset,algorithm,loss_feedback,test accuracy,State,learning_rate,learning_rate_backward,train accuracy,seed,activation_function,epochs_backward,stepsize
11,CIFAR100_BP,CIFAR100,BP,DTP,0.2361,finished,0.004,0.001,0.34102,5,tanh,5,0.01
41,CIFAR100_BP,CIFAR100,BP,DTP,0.2400,finished,0.004,0.001,0.34256,2,tanh,5,0.01
168,CIFAR100_BP,CIFAR100,BP,DTP,0.2372,finished,0.004,0.001,0.34252,3,tanh,5,0.01
393,CIFAR100_BP,CIFAR100,BP,DTP,0.2348,finished,0.004,0.001,0.33832,4,tanh,5,0.01

# CCL

In [23]:
# MNIST
PATH = "./wandb_classification_CCL_0502.csv"
dataset = pd.read_csv(PATH)
ds = dataset[dataset["dataset"] == "MNIST"]
# del ds["Runtime"]
ds = ds[ds.grad_clip_B == 1]
ds = ds[ds.grad_clip_F == 1]
ds = ds[ds.lr_B == 2]
ds = ds[ds.lr_F == 2]
ds = ds[ds.epochs == 100]
ds = ds[~ds.duplicated()]
ds = ds.dropna()
print(ds.test_acc.mean(), ds.test_acc.std())

0.9815400000000001 0.0011107554986484476

In [24]:
# MNIST
PATH = "./wandb_classification_CCL_0502.csv"
dataset = pd.read_csv(PATH)
ds = dataset[dataset["dataset"] == "FashionMNIST"]
# del ds["Runtime"]
ds = ds[ds.grad_clip_B == 1]
ds = ds[ds.grad_clip_F == 1]
ds = ds[ds.lr_B == 2]
ds = ds[ds.lr_F == 2]
ds = ds[ds.epochs == 100]
ds = ds[~ds.duplicated()]
ds = ds.dropna()
print(ds.test_acc.mean(), ds.test_acc.std())

0.879975 0.004778149671757301

In [32]:
# MNIST
PATH = "./wandb_classification_CCL_0502.csv"
dataset = pd.read_csv(PATH)
ds = dataset[dataset["dataset"] == "CIFAR10"]
# del ds["Runtime"]
ds = ds[ds.grad_clip_B == 1]
ds = ds[ds.grad_clip_F == 1]
# ds = ds[ds.lr_B == 2]
# ds = ds[ds.lr_F == 2]
ds = ds[ds.epochs == 100]
# ds = ds[~ds.duplicated()]
ds = ds.dropna()
print(ds.test_acc.mean(), ds.test_acc.std())

0.42985652173913047 0.07264823578886258

In [33]:
ds

,Name,dataset,method,test_acc,Created,State,Runtime,GradC,act_B,act_F,...,grad_clip_B,grad_clip_F,loss_scale_C,lr_B,lr_F,warmup,seed,bw_bn,val_acc,best_epoch
96,CIFAR10_classification_CCL,CIFAR10,CCL,0.5233,2024-05-01T13:23:56.000Z,finished,2002,0,elu,elu,...,1.0,1.0,0.5,0.5,0.5,100,4,1,0.4874,93.0
97,CIFAR10_classification_CCL,CIFAR10,CCL,0.5233,2024-05-01T13:57:27.000Z,finished,2000,0,elu,elu,...,1.0,1.0,0.5,0.5,0.5,100,4,2,0.4874,93.0
98,CIFAR10_classification_CCL,CIFAR10,CCL,0.5225,2024-05-01T10:09:19.000Z,finished,1978,0,elu,elu,...,1.0,1.0,0.5,0.5,0.5,100,2,1,0.4720,96.0
99,CIFAR10_classification_CCL,CIFAR10,CCL,0.5225,2024-05-01T15:45:02.000Z,finished,1200,0,elu,elu,...,1.0,1.0,0.5,0.5,0.5,100,1,2,0.4720,96.0
100,CIFAR10_classification_CCL,CIFAR10,CCL,0.5225,2024-05-01T10:42:25.000Z,finished,1829,0,elu,elu,...,1.0,1.0,0.5,0.5,0.5,100,2,2,0.4720,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,CIFAR10_classification_CCL,CIFAR10,CCL,0.3015,2024-05-01T06:14:52.000Z,finished,1557,0,elu,elu,...,1.0,1.0,0.5,2.0,2.0,100,0,1,0.2368,26.0
207,CIFAR10_classification_CCL,CIFAR10,CCL,0.3015,2024-05-01T06:40:56.000Z,finished,1558,0,elu,elu,...,1.0,1.0,0.5,2.0,2.0,100,0,2,0.2368,26.0
208,CIFAR10_classification_CCL,CIFAR10,CCL,0.2945,2024-05-01T07:07:01.000Z,finished,1516,0,elu,elu,...,1.0,1.0,0.5,2.0,2.0,100,1,1,0.2634,37.0
209,CIFAR10_classification_CCL,CIFAR10,CCL,0.2945,2024-05-01T07:32:24.000Z,finished,1512,0,elu,elu,...,1.0,1.0,0.5,2.0,2.0,100,1,2,0.2634,37.0
210,CIFAR10_classification_CCL,CIFAR10,CCL,0.2626,2024-05-01T19:42:39.000Z,finished,11992,0,elu,elu,...,1.0,1.0,0.5,1.0,1.0,100,4,1,0.1826,81.0